import {
  Leaf,
  Oven,
  IconProps,
  Bicycle,
  Camera,
  WifiHigh,
  PawPrint,
  HairDryer,
  Smiley,
  SmileyWink,
  Fan,
  ArrowLeft,
  ArrowRight,
  FileX,
  User,
  Users,
  CreditCard,
  Circle,
  CheckCircle,
  DeviceMobileSpeaker,
  CallBell,
  PersonSimpleThrow,
  PersonArmsSpread,
  Briefcase,
  Baby,
  Siren,
  Popcorn,
  Confetti,
  HandsPraying,
  SprayBottle,
  SuitcaseRolling,
  Champagne,
  SecurityCamera,
  GlobeHemisphereWest,
  Laptop,
  Van,
  FlowerLotus,
  Prohibit,
  ArrowFatRight,
  ArrowFatLeft,
  CigaretteSlash,
} from "@phosphor-icons/react";
type IconComponent = (props: IconProps) => JSX.Element;
export const CustomIcons: Record<string, IconComponent> = {
  leaf: (props: IconProps) => <Leaf {...props} />,
  oven: (props: IconProps) => <Oven {...props} />,
  bicycle: (props: IconProps) => <Bicycle {...props} />,
  camera: (props: IconProps) => <Camera {...props} />,
  wifi: (props: IconProps) => <WifiHigh {...props} />,
  fan: (props: IconProps) => <Fan {...props} />,
  smartphone: (props: IconProps) => <DeviceMobileSpeaker {...props} />,
  arrowLeft: (props: IconProps) => <ArrowLeft {...props} />,
  arrowRight: (props: IconProps) => <ArrowRight {...props} />,
  fileX: (props: IconProps) => <FileX {...props} />,
  user: (props: IconProps) => <User {...props} />,
  smiley: (props: IconProps) => <Smiley {...props} />,
  smileyWink: (props: IconProps) => <SmileyWink {...props} />,
  users: (props: IconProps) => <Users {...props} />,
  circle: (props: IconProps) => <Circle {...props} />,
  checkCircle: (props: IconProps) => <CheckCircle {...props} />,
  Amenities: (props: IconProps) => <HairDryer {...props} />,
  Dining: (props: IconProps) => <CallBell {...props} />,
  Recreation: (props: IconProps) => <PersonSimpleThrow {...props} />,
  Accessibility: (props: IconProps) => <PersonArmsSpread {...props} />,
  BusinessServices: (props: IconProps) => <Briefcase {...props} />,
  ChildrensServices: (props: IconProps) => <Baby {...props} />,
  EmergencyServices: (props: IconProps) => <Siren {...props} />,
  Entertainment: (props: IconProps) => <Popcorn {...props} />,
  Events: (props: IconProps) => <Confetti {...props} />,
  GuestServices: (props: IconProps) => <HandsPraying {...props} />,
  Housekeeping: (props: IconProps) => <SprayBottle {...props} />,
  Luggage: (props: IconProps) => <SuitcaseRolling {...props} />,
  PetServices: (props: IconProps) => <PawPrint {...props} />,
  Miscellaneous: (props: IconProps) => <CreditCard {...props} />,
  Party: (props: IconProps) => <Champagne {...props} />,
  Security: (props: IconProps) => <SecurityCamera {...props} />,
  Sustainability: (props: IconProps) => <GlobeHemisphereWest {...props} />,
  Technology: (props: IconProps) => <Laptop {...props} />,
  Transportation: (props: IconProps) => <Van {...props} />,
  WellnessandSpa: (props: IconProps) => <FlowerLotus {...props} />,
  CancellationPolicy: (props: IconProps) => <Prohibit {...props} />,
  CheckInTime: (props: IconProps) => <ArrowFatRight {...props} />,
  CheckOutTime: (props: IconProps) => <ArrowFatLeft {...props} />,
  Nosmoking: (props: IconProps) => <CigaretteSlash {...props} />,
  PetPolicy: (props: IconProps) => <PawPrint {...props} />,
};
