name: Trigger auto deployment for jambo-booking-app

on:
  push:
    branches: 
      - master
    paths:
      - '**'
      - '.github/workflows/jambo-booking-app-AutoDeployTrigger-cf0ec160-9831-44b1-8b12-23ed52a417a9.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.JAMBOBOOKINGAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.JAMBOBOOKINGAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.JAMBOBOOKINGAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        run: |
          az acr login --name ${{ secrets.JAMBOBOOKINGAPP_REGISTRY_NAME }}
          docker build -t ${{ secrets.JAMBOBOOKINGAPP_REGISTRY_URL }}/jambo-booking-app:${{ github.sha }} .
          docker push ${{ secrets.JAMBOBOOKINGAPP_REGISTRY_URL }}/jambo-booking-app:${{ github.sha }}

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update -n jambo-booking-app -g JamboBookingApp --image ${{ secrets.JAMBOBOOKINGAPP_REGISTRY_URL }}/jambo-booking-app:${{ github.sha }}
